redhat-developer/observability-operator

- go.mod
- go.sum
update to new repository location
> update go modules path

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: release v3.0.7

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v3.0.8

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
- controllers/reconcilers/configuration/prometheus.go
- go.sum
> fix: allow storage sizes <250Gi

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
This change updates bundle for v3.0.11 release
> fix: correct v3.0.11 bundle

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle/manifests/observability.redhat.com_observabilities.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
- go.mod
> feat: prepare v3.0.12

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v3.0.13

- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle/manifests/observability.redhat.com_observabilities.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v3.0.14

- controllers/observability_controller.go
After working at this for a while ive discovered that the storage class for Prometheus uses the default storage class of the cluster. So Ive instead changed the checks to check if the operator is being run on crc rather than checking individual storage classes.
> Added a check for other cloud providers

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v3.0.15

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle_history.txt
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v3.0.16

- controllers/reconcilers/logging_installation/logging_installation_reconciler.go
This change fixes issue where during upgrade an applied CR can have a nil value for `disableLogging`.
- If the applied CR has no value for `disableLogging` the Operator will skip installation of the Cluster Logging Operator. 
- If the applied CR does have an explicit value for `disableLogging` then this value can be used by the Operator
**Note:** Currently the Operator is setup to install Cluster Logging Operator for Managed Kafka service only. Further work would be required to support other services.
> Set default disableLogging value for applied CR during upgrade

- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> Prepare v4.0.0

- controllers/reconcilers/logging_installation/logging_installation_reconciler.go
The logging forwarder input namespaces were not updated, because every change to the CR needs to happen inside the `CreateOrUpdate` callback function.
> fix: udpated input namespaces for the logging forwarder

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v4.0.4 release

- controllers/reconcilers/configuration/configuration_reconciler.go
Also skip lookup of Grafana CR when DescopedModeEnabled is true
Signed-off-by: Michael Edgar <medgar@redhat.com>
> fix: use CR's Prometheus namespace to check for Alertmanager CR

- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- main.go
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
Adding health and ready check for manager pod to ensure manager is up and running.
> Adding health and ready check for manager

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle/manifests/observability.redhat.com_observabilities.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
> feat: prepare v4.1.0 release

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
Prepares v4.1.1 release including fix for updating log forwarding CR
> feat: prepare release v4.1.1

- controllers/reconcilers/prometheus_installation/prometheus_installation_reconciler.go
Updating the Prometheus Operator index image version to v1.0.1
> chore: update Prometheus Operator index image version

- Dockerfile
Update Dockerfile Go version to 1.19
> build: update Go version in dockerfile

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
Release for commit https://github.com/redhat-developer/observability-operator/commit/633383ab0d2f45b9e06a066576d26ca0b3911028
> prepare release v4.2.1
