- Makefile
- bundle_history.txt
add target for building index image via opm. This also downloads the opm binary if not installed.
> add target for building index image via opm

- controllers/reconcilers/configuration/alertmanager.go
- controllers/reconcilers/configuration/grafana.go
- controllers/reconcilers/configuration/prometheus.go
This pr relates to this change comment -> https://github.com/integr8ly/integreatly-operator/pull/2070#issuecomment-931442219
oauth 4.2 doesn't work on 4.9
I've tested both 4.9 and 4.8 on a 4.9 cluster
I think it's safer to go with 4.8 as I haven't tested 4.9 on a 4.8 cluster.
> update all versions of oauth-proxy

- controllers/model/prometheus_resources.go
A previous [PR](https://github.com/redhat-developer/observability-operator/pull/86) added support for overriding selectors so they could be set to nil. However further testing revealed that we actually need to have these selectors be set to an empty object `{}`.
Changed logic in `prometheus_resources.go` to return a blank LabelSelector rather than nil when the spec.selfContained.overrideSelectors is true but the selector is blank.
* Install the Observability Operator locally
* Create an observability CR with the following spec
```yaml
spec:
configurationSelector:
matchLabels:
monitoring-key: middleware
resyncPeriod: 1h
selfContained:
overrideSelectors: true
disableDeadmansSnitch: true
disablePagerDuty: true
disableRepoSync: true
serviceMonitorNamespaceSelector:
matchExpressions:
- key: …
```
> Change override to return empty object instead of nil.

- main.go
Resolves [MGDSTRM-6173](https://issues.redhat.com/browse/MGDSTRM-6173)
Check added to `main.go` to ensure webhook server is reachable before progressing operator setup.
**Using OSD cluster**
1. Create new CatalogSource using the following image:
`quay.io/vmanley/observability-operator-index:v3.0.8`
2. Install the operator using the CatalogSource
3. Observability stack should install with no errors
4. Both the Observability and Prometheus CRs should contain the following storage claim:
```
storage:
volumeClaimTemplate:
metadata:
name: managed-services
spec:
resources:
requests:
storage: 50Gi
```
5. A Persistent Volume Claim should be created with prefix `managed-services-` and a capacity of `50GiB`
**Using CRC**
1. Follow steps 1 - 4 as above
2. No Persistent Volume Claim will be observed …
> fix: add webhook server check

- api/v1/observability_types.go
- config/crd/bases/observability.redhat.com_observabilities.yaml
- controllers/model/prometheus_resources.go
- controllers/reconcilers/configuration/prometheus.go
The RHOAM product needs to be able to add a bearer token to the BlackboxExporter ConfigMap as part of [MGDAPI-2282](https://issues.redhat.com/browse/MGDAPI-2282).
Added the field `BlackboxBearerTokenSecret` to the `SelfContained` struct of the Observability CR Spec that can hold the name of a secret whose token will act as a bearer token for the BlackboxExporter. The token is then extracted from the secret and inserted into the blackbox config.
- Install the Observability Operator locally
- Create a ServiceAccount in the target namespace and note the name of the secret that is created for the ServiceAccount
- Create an observability CR with the following Spec, replacing {secret-name} with the name from the step above:
```yaml
spec:
configurationSelector:
matchLabels:
monitoring-key: …
```
> Added support to include bearer token in blackbox exporter ConfigMap.

- go.mod
- go.sum
PR should resolve Dependabot alerts for 
- github.com/containerd/containerd
- github.com/opencontainers/image-spec
go.mod and go.sum updated to versions recommended in the alerts.
Verified by running locally on CRC
> fix: update deps to resolve security alert

- Dockerfile
- main.go
- runners/generic_runner.go
Resolves [MGDSTRM-6173](https://issues.redhat.com/browse/MGDSTRM-6173)
Allows the Operator to avoid conflict with webhooks when adding the Prometheus storage spec
**Using OSD cluster**
1. Create new CatalogSource using the following image:
`quay.io/vmanley/observability-operator-index:v3.0.9`
or create your own from this branch
2. Install the operator using the CatalogSource
3. Observability stack should install with no errors
4. Both the Observability and Prometheus CRs should contain the following storage claim:
```
storage:
volumeClaimTemplate:
metadata:
name: managed-services
spec:
resources:
requests:
storage: 50Gi
```
5. A Persistent Volume Claim should be created with prefix `managed-services-` and a capacity of `50GiB`
**Using CRC**
1. Follow steps 1 - 4 as above
2. No Persistent …
> fix: webhook timing issue

- go.mod
- go.sum
Go.mod updated to fix security alert on opencontainers/runc.
Update follows recommendation contained in alert (update to min v1.0.3)
> Fix security alert for opencontainers/runc

- bundle/manifests/observability.redhat.com_observabilities.yaml
Adds the `blackboxBearerTokenSecret` string to `bundle/manifests/observability.redhat.com_observabilities.yaml` which I forgot to include in #94
> Adds blackboxBearerTokenSecret string to bundle

- .github/workflows/go.yml
- Dockerfile
- README.md
- go.mod
Main purpose of this PR is to update the go version. The go.mod was edited to update the go version to 1.16
Also Dockerfile was investigated as part of the same task and it was discovered that the images used for:
* [registry.access.redhat.com/ubi8/go-toolset](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?tag=1.13.15-1&push_date=1599577036000)
* [registry.access.redhat.com/ubi8/ubi-minimal](https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?tag=8.4-200&push_date=1621383400000&container-tabs=overview)
had possible security issues.
Image tags updated to latest images.
> update go version and Dockerfile

- Makefile
- README.md
- templates/crc-secret-template.yml
- templates/secrets-template.yml
This change allows users to setup and deploy required secrets for deployment.
The following make targets have been added to the Makefile:
```
make deploy/secrets
```
```
make deploy/crc/secret
```
`make deploy/secrets` can setup and deploy the following secrets:
* `observatorium-configuration-red-hat-sso`
* `kafka-observability-configuration`
* `redhat-managed-kafka-pagerduty`
* `redhat-managed-kafka-deadmanssnitch`
`make deploy/crc/secret` configures and deploys the `grafana-datasource` secret to the `openshift-monitoring` namespace.
Verification (OSD or CRC)
1. Use the `make deploy/secrets` target against your cluster.
2. The following secrets should be created in your current namspace/project:
- `observatorium-configuration-red-hat-sso`
- `kafka-observability-configuration`
- …
> Add make targets to deploy required secrets

- api/v1/index.go
- controllers/model/prometheus_resources.go
- controllers/observability_controller.go
- controllers/reconcilers/configuration/prometheus.go
This change is to increase the default Prometheus storage size from `50Gi` to `250Gi`. Also this change will allow the Prometheus storage size to be overridden by value contained in Observability resources (see https://github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/pull/138)
**Using OSD cluster**
1. Run this branch locally against an OSD cluster
2. Allow the operator to complete installation and check the Prometheus CR for it's storage value. CR should contain the default 250Gi storage value:
```
storage:
volumeClaimTemplate:
metadata:
name: managed-services
spec:
resources:
requests:
storage: 250Gi
```
4. Find the required `kafka-observability` secret in your namespace and edit the `repository` and `tag` fields as follows:
repository: …
> feat: increase default Prom storage size and logic to allow resources override

- controllers/reconcilers/configuration/prometheus.go
- controllers/reconcilers/prometheus_configuration/prometheus_configuration_reconciler.go
- controllers/utils/reconciler_utils.go
- go.mod
This change is to allow the Operator to support Openshift v4.10+.
In Openshift v4.10.0 the `grafana-datasources` secret required by the Operator was updated:
- Name has changed to `grafana-datasources-v2`
- The `prometheus.yaml` data has been restructured. `basicAuthPassword`  has now been included as part of a new `secureJsonData` field
Example of `prometheus.yaml` in Openshift 4.9
```
{
"apiVersion": 1,
"datasources": [
{
"access": "proxy",
"basicAuth": true,
"basicAuthPassword": "eArKGnoEuIBKVvTz1Fb+o+t7LupNWgg1tBMRRbQ+tOOMScI9A0R+BaqT7yN8x0459xEDNNujKOoM1ztHgfYXvn81uyFfHYfMWHx1+jWBO6md1ySCTtFvLIs/OgDjAaYWXb584jYHmO/57l+JskqwxdVk/vCFsTLuTIZmgYx+BZB+nF720AmexFy2f55b+LZautm8MVUW25SdjCR+JsBYTprZLqXKPV0qpA3/es1dWPXVfWfi2+ss0iX/0GJfk3Uq4AEMnrsMoHKtevLka6fRgrSWfl/CIKCw5D+PoCB55ryh0gLN9TZFMPGc …
```
> Allow operator to support Openshift 4.10

- controllers/reconcilers/configuration/alertmanager.go
A check to see if SMTP is enabled and if the to and from email addresses are populated already exists in the `createGlobalConfig` section, so there is no need to check again, preventing duplicate log lines.
> Remove redundant else block

- Makefile
- api/v1/index_test.go
- api/v1/observability_types_test.go
- api/v1/observability_webhook.go
- api/v1/observability_webhook_test.go
Jira: [MGDSTRM-8328](https://issues.redhat.com/browse/MGDSTRM-8328)
This change increases testing coverage of api/v1 package. 
| | Current testing coverage | Coverage with this change |
| --- | --- | --- |
| api/v1/index.go | 0.0% | 100.0% |
| api/v1/observability_types.go | 6.7% | 100.0% |
| api/v1/observability_webhook.go | 56.0% | 81.5% |
| **Overall** | **3.8%** | **89.1%** |
It was found that the ValidateUpdate method in `observability_webhook.go` was performing as expected (the "cannot set..." and "cannot unset..." errors were not being returned in appropriate situations) so this method has been refactored to improve this.
Also the presence of `zz_generated.deepcopy.go` in this package distorted testing coverage (`make test/unit` reported 8.9% coverage despite all relevant files …
> test: add tests to api/v1

- Makefile
- controllers/model/alertmanager_resources.go
- controllers/model/alertmanager_resources_test.go
- controllers/model/grafana_resources.go
- controllers/model/grafana_resources_test.go
- controllers/model/prometheus_resources.go
- controllers/model/prometheus_resources_test.go
- controllers/model/promtail_resource_test.go
- controllers/model/token_refresher_resources_test.go
- controllers/model/token_resources_test.go
- controllers/observability_controller.go
Jira: [MGDSTRM-8329](https://issues.redhat.com/browse/MGDSTRM-8329)
This change increases testing coverage of controllers/model package. 
| | Current testing coverage | Coverage with this change |
| --- | --- | --- |
| controllers/model/alertmanager_resources.go | 0.0% | 100.0% |
| controllers/model/grafana_resources.go | 0.0% | 100.0% |
| controllers/model/prometheus_resources.go | 6.1% | 83.2% |
| controllers/model/promtail_resources.go | 0.0% | 100% |
| controllers/model/token_refresher_resources.go | 0.0% | 100% |
| controllers/model/token_resources.go | 0.0% | 100% |
| **Overall** | **3.8%** | **90.1%** |
Also includes updates to remove AlertManagerStorageSpec from default Observability and remove default value for AlertManagerDefaultStorage. Verified that CR value for alert manager …
> test: added tests to controllers/model

- controllers/reconcilers/configuration/prometheus.go
- controllers/utils/reconciler_utils.go
- controllers/utils/reconciler_utils_test.go
Jira [MGDSTRM-8341](https://issues.redhat.com/browse/MGDSTRM-8341)
This change increases testing coverage of controllers/utils package. 
| | Current testing coverage | Coverage with this change |
| --- | --- | --- |
| controllers/utils/reconciler_utils.go | 0.0% | 39.6% |
| **Overall** | **0.0%** | **39.6%** |
- On `main` run `make test/unit`. Output should show that this package currently has no testing files
- For example: 
- `?   github.com/redhat-developer/observability-operator/v3/controllers/utils    [no test files]`
- On this PR run `make test/unit PKG=controllers/utils`. Output should contain testing coverage for controllers/reconcilers/token
- For example: 
- `ok      github.com/redhat-developer/observability-operator/v3/controllers/reconcilers/token     0.008s  coverage: 39.6% …
> test: add tests to controllers/utils

- Makefile
- controllers/reconcilers/token/token_manager_test.go
Jira [MGDSTRM-8339](https://issues.redhat.com/browse/MGDSTRM-8339)
This change increases testing coverage of controllers/reconcilers/token package. 
| | Current testing coverage | Coverage with this change |
| --- | --- | --- |
| controllers/reconcilers/configuration/token/token_manager.go | 0.0% | 9.2% |
| controllers/reconcilers/configuration/token/token_reconciler.go | 0.0% | ignored |
| **Overall** | **0.0%** | **9.7%** |
- On `main` run `make test/unit`. Output should show that this package currently has no testing files
- For example: 
- `?   github.com/redhat-developer/observability-operator/v3/controllers/reconcilers/token    [no test files]`
- On this PR run `make test/unit PKG=controllers/reconcilers/token`. Output should contain testing coverage for …
> test: add tests to controllers/reconcilers/token

- Makefile
This PR is to close off a number of unit test Jiras within the overall testing epic. [Epic link](https://issues.redhat.com/browse/MGDSTRM-1050)
A number of packages contain files unsuitable for unit testing and so can be ignored for unit test coverage. This change adds these to the list of ignored files/packages in the `make test/unit` target.
**Packages/files to ignore**
- controllers/reconcilers/alertmanager_installation
- controllers/reconcilers/csv
- controllers/reconcilers/grafana_configuration
- controllers/reconcilers/grafana_installation
- controllers/reconcilers/prometheus_installation
- controllers/reconcilers/promtail_installation
- controllers/token
- controllers/reconcilers/prometheus_configuration
> test: ignore untestable files from unit test coverage

- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
This PR changes the image pull policy to `IfNotPresent` for deployments.
**Verification**
- Deploy latest version of Observability Operator (v3.0.10)
- Note the `ImagePullPolicy` in the `observability-operator-controller-manager` YAML is set to `Always`
- Deploy the Operator using an image including this change (image available at `quay.io/vmanley/observability-operator-index:v3.0.11`)
- Note the `ImagePullPolicy` in the `observability-operator-controller-manager` YAML is now set to `IfNotPresent`
> chore: change image pull policy to 'IfNotPresent'

- api/v1/index.go
- api/v1/observability_types.go
- controllers/model/grafana_resources.go
- controllers/model/grafana_resources_test.go
- controllers/reconcilers/configuration/grafana.go
The changes made are to make the Grafana Version configurable through the index.json located [here](https://github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/blob/main/resources/index.json) in the observability resources repo. 
By adding the **grafanaVersion** field followed by version tag.
If left empty or blank the Grafana Operator uses a hard coded Grafana Version defined within itself.
> Making the Grafana Version Configurable.

- controllers/reconcilers/configuration/prometheus.go
- controllers/utils/reconciler_utils.go
- controllers/utils/reconciler_utils_test.go
- go.mod
- go.sum
Jira: [MGDSTRM-8903](https://issues.redhat.com/browse/MGDSTRM-8903)
This change is to improve the upgrade process from Openshift from 4.9 to 4.10. Specfically it changes the handling of the required Grafana datasources secret which is modified during this particular upgrade process
> Improve grafana datasources secret handling

- api/v1/observability_types.go
- config/crd/bases/observability.redhat.com_observabilities.yaml
- controllers/model/grafana_resources.go
- controllers/model/grafana_resources_test.go
- controllers/reconcilers/configuration/grafana.go
Added the functionality of configuring the Version of Grafana that is used through the selfContained part of the Observability Stacks selfContained section in the yaml. You can test this in crc by adding ```grafanaVersion: 8.4.1``` as above.
> Self Contained Grafana Version Configuration

- bundle/manifests/observability-operator-federation-reader_rbac.authorization.k8s.io_v1_rolebinding.yaml
- controllers/model/prometheus_resources.go
- controllers/model/prometheus_resources_test.go
- controllers/reconcilers/configuration/prometheus.go
This PR leaves the current behaviour as-is and adds a fallback for when the operator cannot find either grafana secret to use a bearer_token_file to access the cluster prometheus.
To operator-federation-reader role is to allow the operator to access the cluster prometheus through bearer token.
I've tested using grafana-datasources-v2 and deleting the secret and confirming the scrape config then correctly includes the bearer_token_file var.
Verification:
1. Install the operator
2. In a separate window continually delete the grafana-datasource-v2 secret
3. Verify that the bearer_token_file var exists in the additional-scrape-config.yaml configmap
> Fallback to bearer token if no secret exists

- Dockerfile
To resolve image vulnerabilities, the following versions are updated in Dockerfile:
- ubi-minimal:8.5 => ubi-minimal:8.6
- go-toolset:1.16.7 => go-toolset:1.17.10
> Update ubi image and go toolset version in Dockerfile

- CONTRIBUTING.md
- DCO
Adding DCO to align with redhat-developer organisation guidelines
> chore: add DCO

- config/rbac/role.yaml
- controllers/observability_controller.go
- controllers/reconcilers/configuration/alertmanager.go
- controllers/reconcilers/configuration/grafana.go
- controllers/reconcilers/configuration/prometheus.go
- controllers/reconcilers/configuration/token_refresher.go
Jira: [MGDSTRM-9608](https://issues.redhat.com/browse/MGDSTRM-9608)
Adds `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` annotation to relevant pods (alertmanager, prometheus and grafana) created by Operator
> Add pod eviction annotations to relevant Observability pods

- Makefile
- controllers/reconcilers/configuration/token_refresher.go
- controllers/reconcilers/prometheus_installation/prometheus_installation_reconciler.go
- controllers/reconcilers/prometheus_installation/prometheus_installation_reconciler_test.go
- go.mod
- go.sum
Jira: [MGDSTRM-9688](https://issues.redhat.com/browse/MGDSTRM-9688), [MGDSTRM-9512](https://issues.redhat.com/browse/MGDSTRM-9512)
This change directs the Operator to install Prometheus Operator from maintained community index instead of previous custom index.
The version of the Prometheus Operator installed is also upgraded from `v0.45.0` to `v0.56.3`.
Also adds initial implementation of unit testing using fake k8s client.
Fresh install:
* Run this PR locally (CRC/remote cluster)
* Check that version of Prometheus Operator installed is `v0.56.3`
* Ensure there are no errors logged by Observability Operator
* Ensure alertmanager and prometheus routes are created and functional.
Upgrade from v3.0.15:
* Install v3.0.15 of the Operator using the RHOAS image …
> feat: switch to community Prometheus Operator index and update version

- controllers/model/logging_resources.go
Add a toleration to the fluentd collector pods to tolerate a taint added to the nodes.
_The toleration added to the clusterLogging CR_
_The toleration rendered down to the collector daemonset_
> add toleration for node taint to unblock fluentd pods

- controllers/reconcilers/logging_installation/logging_installation_reconciler.go
Previously the logic for the clusterLogForwarder was appending a new pipeline, this would result in adding a second pipeline rather than creating a single pipeline with both inputs included.
> logforwarder CR should include both inputs in a single pipeline

- controllers/reconcilers/migration/resource_name_migration.go
Fix to avoid situation where Operator tries to migrate an non-existing Grafana CR when the Operator is installed in cluster scope.
- Install the v3.0.14 of Operator in cluster scope by installing in `openshift-operators` namespace. This can be done with a CatalogSource applied to `openshift-marketplace` namespace with the index image `quay.io/rhoas/observability-operator-index:v3.0.14`
- The Operator can be blocked from initialising a Observability CR by applying a ConfigMap with the name `observability-operator-no-init` in the `openshift-operator` namespace
- Apply the following CR:
```
apiVersion: observability.redhat.com/v1
kind: Observability
metadata:
name: observability-stack
labels:
managed-by: observability-operator
spec:
configurationSelector:
matchLabels:
configures: …
```
> Add cluster scope check for Grafana migration

- api/v1/observability_types.go
- config/crd/bases/observability.redhat.com_observabilities.yaml
- controllers/model/grafana_resources.go
- controllers/model/grafana_resources_test.go
- controllers/reconcilers/configuration/grafana.go
* Allow grafana init container to be configurable through the observability CR
* Override grafana init container to use more recent `quay.io/grafana-operator/grafana_plugins_init:0.1.0` due to better image grading by default if not specified in the CR
> feat: configurable grafana init image 

- controllers/reconcilers/configuration/alertmanager.go
- controllers/reconcilers/configuration/grafana.go
- controllers/reconcilers/configuration/prometheus.go
This change updates the `origin-oauth-proxy` image from `v4.8` to `v4.9`.
This version was chosen as it appears to have fewer security vulnerabilities than subsequent available versions
> Update oauth proxy image version

- controllers/reconcilers/grafana_installation/grafana_installation_reconciler.go
Bump default Grafana Operator version from `v3.10.7` to `v3.10.8`
> Bump default Grafana Operator version

- controllers/model/logging_resources.go
- controllers/reconcilers/logging_installation/logging_installation_reconciler.go
Make sure that updates to the cluster log forwarder CR are applied, by assigning all the spec fields inside the `CreateOrUpdate` function.
This changes assumes that the CR is completely managed by the OO and it doesn't need to preserve any pre-existing state (which wasn't the case earlier). For this reason, I also removed all the appends (to e.g. the pipelines spec), because we know exactly what pipelines we want to configure and we can simply overwrite whatever is there. We never want to append.
> fix: apply updates to cluster log forwarder cr

- .github/workflows/pr-check.yaml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
> Pin 3rd-party actions to SHA1

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/observability-operator.clusterserviceversion.yaml
Prepares v4.1.2 which includes updated images for Prometheus Operator index and token refresher
> Prepare release v4.1.2

- api/v1/observability_types.go
- config/crd/bases/observability.redhat.com_observabilities.yaml
- controllers/reconcilers/configuration/alertmanager.go
- controllers/reconcilers/configuration/grafana.go
- controllers/reconcilers/configuration/origin_proxy.go
- controllers/reconcilers/configuration/origin_proxy_test.go
- controllers/reconcilers/configuration/prometheus.go
* Allow configuring oauth proxy image via Observability CR
* Default image is used when not specificed in CR
* Custom oauth proxy image is used when specified in CR
> feat: allow configuring origin oauth proxy image

- controllers/reconcilers/configuration/configuration_reconciler.go
This change is to avoid situations where Operator fails to fetch resources from resource container if access token is present in configuration secret
> Change getResourceUrl to check repo url rather than access token

- controllers/observability_controller.go
removes all finalizers and disables cleanup if the CR was auto generated. Finalizers cause issues with namespace deletion and without the finalizer we will need to refactor to using owner references for all resources to do cleanup.
> fix: disable cleanup when CR is auto generated

- controllers/reconcilers/configuration/token_refresher.go
- controllers/reconcilers/prometheus_installation/prometheus_installation_reconciler.go
- controllers/reconcilers/prometheus_installation/prometheus_installation_reconciler_test.go
Bumping Prometheus Operator version to `v0.56.3`.
Note: This update of the Prometheus Operator requires a resync of the configuration resources. Therefore updating to this change can require a full `spec.resyncPeriod` as given in the Observability CR.
> Update Prometheus Operator version

- Makefile
- README.md
- api/v1/index.go
- api/v1/index_test.go
- config/samples/secrets/observatorium-configuration-red-hat-sso.yaml
- controllers/reconcilers/configuration/token_refresher.go
- controllers/reconcilers/token/token_manager.go
This change removes requirement for observatorium config to contain a value for `tenant`.
> fix: remove requirement for tenant value in observatorium config

- controllers/reconcilers/logging_installation/logging_installation_reconciler.go
- Collect logs for ingress namespace
- - We have a custom ingress so we should collect logs for it
- Collect logs for observability namespace
- - A namespace we manage so we should collect the logs
- Group by logType
- - This will make precreation of resources much more straightforward 
_Verification_
1. Deploy this to an OSD cluster.
2. Verify the new namespaces are in the clusterLogForwarder resource
3. Verify the GroupBy var in the ClusterlogForwarder is `logType`
> collect logs for ingress and observability namespaces and group by logtype
